site_name: cldf-ldd
site_url: https://fl.mt/cldf-ldd
theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - assets/colors.css
markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  version:
    provider: mike
plugins:
  - search
  - table-reader
  - awesome-pages
repo_url: https://github.com/fmatter/cldf-ldd